esm-dev/esm.sh

embed/test/simple_test.js
embed/test/testing.js

feat: add simple test

---

server/nodejs.go

The latest node version is `14.17.3` as of writing and this fixes #86.

Update node version to the latest

---

Dockerfile
README.md

This is an example Dockerfile that I've used to deploy my own mirror. I reckon others would find it useful as well.
Related: https://github.com/postui/esm.sh/issues/73

Add example Dockerfile

---

.github/ISSUE_TEMPLATE/failing-import.md

Create an issue template to report failing imports faster

Add an issue template for failing imports

---

server/server.go

pretty self explanatory, to cover non-standard environment (like mine).

feat: allow log-dir to be configured

---

embed/index.html

Yes, I'm using `replaceAll`, but that's because this entire project is about embracing modern javascript ;)

feat: make index.html a little more self hosting friendly

---

server/query.go

Browsers love requesting this, like all the time

do not try to build /favicon.ico

---

embed/test/testing.js

Added a [pixi.js ](https://pixijs.com/) example
Added a [three.js](https://threejs.org/) example
) example

tests for pixi.js and three.js

---

embed/test/testing.js

fix: minor tweak to remove deprecation warning

---

embed/test/testing.js

added @material-ui/core test

---

server/storage/cache_memory_lru.go
server/storage/fs_local_lru.go
server/storage/fs_s3.go

none of this should be to default code paths

Misc fixes

---

server/embed/polyfills/node_process.js

PR is open https://github.com/defunctzombie/node-process/pull/84 but not merged
Upstream seem to be inactive since 2017

node_process: add emitWarning

---

server/storage/cache_memory_lru.go

lru cache fix by using the library's lock mechanism

lru cache fix

---

.gitignore
server/nodejs.go
server/server.go

set npm registry from cli , and use it at first， do not use the global npm config registry.

set npm registry from cli , and use it at first

---

server/embed/polyfills/node_process.js

This old process polyfill uses a fix for setTimeouts which was originally made to work on some insanely niche smart TV's. We don't care about that as our minimal entry point is ESM anyways, so I replaced it with queueMicrotask which has very similar support ranges. This was first done by `mathiasvr` in [process-fast](https://github.com/mathiasvr/process-fast) so I changed the copyright to his, even tho it's just 1 line of code.
Why this matters?
I'll quote [Endless ](https://github.com/jimmywarting) on this matter:
The problem is with `process` browserified version of `process.nextTick` it uses a `setTimeout(fn, 0)` as a fallback. The `setTimeout` is delayed well enough in foreground to strangle the speed from 6-7000 kb/s down to just 400 kb/s when one tab is hidden "to save resources". …

perf: process: replace timeout with queueMicrotask

---

server/node_services.go
test/issue-454/issue-454.test.ts

ref: https://github.com/ije/esm.sh/issues/454

Fix build (close #454)

---

server/embed/style.css

When OS prefers dark mode, it the site will automatically look dark.
TLDR: my eyes ;-;

feat: dark mode website

---

HOSTING.md

The HOSTING doc is out of date
Updated the doc to up to date and added more information for server options.

docs: update

---

server/build.go
server/config/config.go
server/esm.go
server/handler.go
server/nodejs.go
server/utils.go

CPU profiling

---

server/consts.go
test/ipfs-dependencies/ipfs-dependencies.test.ts
test/issue-548/issue-548.test.ts

Continuing from #548, I have just kept trying to import ipfs and kept hitting new modules.
IPFS still doesn't work but I have fixed these two.

Fixes netmask and xml2js

---

server/build_helpers.go
server/pkg.go
test/issue-578/issue-578.test.ts

Fix invalid type URL if submodule is main entry

---

server/nodejs.go

Improve automatic detection to handle arm64. It was not working on darwin/arm64.

fix arch for darwin arm64

---

server/build.go

fix: write npmrc file if NpmRegistry is set - fixes #737

---

server/utils.go

Allow JS file validation to parse TS.

Fixes #803

---

test/unocss/unocss.test.ts

the spec changes to `with` for import attributes

fix: correct import attributes

---

server/npm.go

Fix for https://github.com/esm-dev/esm.sh/issues/821

Fix github registry metadata fetching

---

HOSTING.md

:memo: Update HOSTING.md

---

README.md

See https://openjsf.org/blog/nodejs-security-progress-report-august-2024

docs: remove reference to eliminated flag

---

.github/workflows/deploy.yml
HOSTING.md
scripts/deploy-ci.sh
scripts/deploy.sh
server/nodejs.go
server/router.go
server/utils.go

get rid of supervisor dependency on deployment

deploy: Use systemd

---

README.md
scripts/deploy-ci.sh
server/build.go
server/build_resolver.go
server/build_rewriter.go
server/consts.go
server/dts_lexer.go
server/dts_transform.go
server/npm.go
test/issue-649/test.ts

- replace `window` with `globalThis`
- use `node:xxx` instead of `http://esm.sh/@types/node/xxx.d.ts`

Suppport Deno 2

---

server/build.go
server/build_resolver.go
server/build_rewriter.go
server/cjs_module_lexer.go
server/dts_transform.go
server/router.go
test/fix-url/test.ts
test/issue-907/test.ts

this pr adds support of [import attributes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import/with):
```
import data from "./data.json" with { type: "json" };
```
close #907

Support import attributes

---

server/build.go
server/build_resolver.go
server/dts_transform.go
server/legacy_router.go
server/path.go
server/router.go
server/server.go
test/fix-url/test.ts

```
https://raw.esm.sh/react -> https://raw.esm.sh/react@19.0.0/index.js
```
close https://github.com/esm-dev/esm.sh/issues/950

Fix package entry url with `?raw` flag

---

server/build.go
server/build_resolver.go
server/path.go
server/router.go
test/jsr/std.test.ts

Fix jsr types

---

server/build.go
server/build_resolver.go
server/module.go
test/build-args/external.test.ts

Fix external all(*) resolving

---

server/build_resolver.go
server/legacy_router.go
server/module.go
test/gh/streamlit.test.ts
test/types-versions/test.ts

Improve build resolver

---

server/build.go
server/build_queue.go
server/build_resolver.go
server/router.go
test/fix-url/test.ts
test/issue-787/test.ts

Improve build resolver for fixing some edge cases

---

server/build.go
server/build_resolver.go
test/issue-763/test.ts

Ignore wildcard exports in package.json

---

server/build.go
server/build_resolver.go
server/cjs_module_lexer.go
server/router.go
test/issue-840/test.ts
test/svelte-5/svelte-compiler.test.ts

Split module that includes `export * from "dep"` statement

---

server/cache.go
server/router.go
server/storage/storage_s3.go
server/storage/storage_s3_test.go
test/bootstrap.ts

Fix S3 Storage signature with `/#/` path

---

server/legacy_router.go
test/legacy-routes/test.ts

Fix legacy routes

---

server/legacy_router.go

Fix legacy router

---

server/build_resolver.go
server/router.go
test/build-args/external.test.ts
test/fix-url/test.ts

Fix build with flag external=*

---

server/legacy_router.go
server/npm.go
test/legacy-routes/test.ts

Fix module path with "/v135/*PKG/"

---

server/build_resolver.go
test/issue-1046/test.ts

Fix `exports` field of package.json resolving

---

server/cache.go
server/cache_test.go

panic: <img width="1081" alt="Image" src="https://github.com/user-attachments/assets/5d7a40df-2083-4e68-aa40-4c96b9d2fe98" />
close #1053

Fix panic caused by the LUR cache

---

server/build_meta.go
server/build_resolver.go

Validate and drop invalid imports in `BuildMeta`

---

server/legacy_router.go
test/legacy-routes/test.ts

Fix legacy types

---

README.md
server/embed/tsx.ts
server/router.go
test/builtin-scripts/test.ts

it's the same script as v135's `esm.sh/run`

Add `esm.sh/tsx` script

---

server/npm.go

Fix invalid `browser` field

---

server/build.go
server/build_resolver.go
server/common/jsonc.go
server/npm.go
test/gh/jsr.test.ts

- use `deno.json`
- resolve `jsr:` specifier (close #1084)

Use `deno.json(c)` on `/gh/*` pattern

---

server/build.go
server/router.go
test/valtown/test.ts

Fix module resolver with `imports` of package.json

---

server/build.go
server/build_analyzer.go
server/build_args.go
server/build_resolver.go
server/build_rewriter.go
server/cjs_module_lexer.go
server/dts_transform.go
server/npm.go
server/router.go
server/server.go
test/valtown/gh.test.ts

Fix module resolver ignoring .ts module

---

server/build_resolver.go
server/path.go
server/utils.go
test/gh/issue-1099.test.ts

Fix `/gh/*` commitish resolving

---

server/build_resolver.go
server/router.go
test/build-args/external.test.ts
test/fix-url/test.ts

Fix `?external` query

---

server/router.go
test/fix-url/test.ts

Fix wasm url related to `import.meta.url`

---

cli/README.md
main.go
server/build_analyzer.go
web/README.md
web/debug.go
web/handler.go
web/release.go
web/utils.go
web/version.go
web/worker.go

- avoid parsing importmap script when the cache is hit
- use dynamic etag suffix in dev mode
- improve preloading

Improve web pkg

---

cli/version.go
main.go

```bash
$ esm.sh --version
esm.sh CLI v136
```

cli: Add version command to display CLI version

---

server/legacy_router.go

Only `Cache-Control` is effective. It's a mistake, regardless whether it is legacy.

fix: There are no such things called `Control-Cache`.

---

server/build.go
server/router.go
test/issue-1191/test.ts

Support import with { type: 'css' }

---

server/build_resolver.go
test/issue-1199/test.ts

Fix browser condition for astring

---

server/build_resolver.go
server/router.go
test/issue-1217/test.ts

Fixes https://github.com/esm-dev/esm.sh/issues/1217
New to this codebase so not sure if I did this in the right place

CSS files should resolve through package.json exports
