esm-dev/esm.sh

server/query.go

Custom headers in browser cross origin requests are omitted unless explicitly whitelisted by the response header 'Access-Control-Expose-Headers'
after this change browser fetch response.headers should contain the X-TypeScript-Types response header and its value

allow reading X-TypeScript-Types reponse header in browser

---

README.md

Moved since https://github.com/denoland/deno/commit/02c6a88d8af08d3e3ae79724d9fb12d4a0f8222f

docs(README): update link to deno.land x-typescript-types-header

---

server/build.go

This fixes the `setImmediate` polyfill to accept rest-style args instead of an array to match [Node.js](https://nodejs.org/docs/latest-v16.x/api/timers.html#timers_setimmediate_callback_args).
```ts
// Actual node.js type signature
type setImmediate = <Args extends any[]>(fn: (...args: Args) => void, ...args: Args);
// Previous esm.sh type signature:
type setImmediate = <Args extends any[]>(fn: (...args: Args) => void, args: Args);
```
The previous behavior would result in `setImmediate` performing differently. If no arguments were passed or the first argument was not iterable, an exception would be thrown. If the first argument was iterable, it'd be passed as a spread result. I created an example npm module and ran it in deno repl as an example:
```js
> const examples = await …
```

Fix setImmediate polyfill args

---

server/server.go

I'm not sure if there's something I'm doing wrong, but when I don't configure this (I do not want https support at all as we do our own TLS termination), it was still failing if the TLS config was passed in.

bugfix: fix attempting to bind to invalid https port

---

server/nodejs.go
server/server.go

Because it's easier to manage permissions when everything that is supposed to be owned by the server process is in the same place. Because the nodejs installation doesn't have any clear requirement to be where it is, figured it could be moved to the etc dir.
Also embedded an npmrc to be picked up by the installed nodejs. There isn't any example to override the npmrc to be embedded during the build process, but that's exactly how I plan do to it.

feat: install nodejs into nodejs-prefix, and make it configurable

---

embed/polyfills/deno_std_node_events.js
embed/polyfills/deno_std_node_stream.js
server/nodejs.go

Similar to #117 but this one adds `stream` and `events` modules, potentially fixing a lot of modules, including `@web3-react/` packages.

feat(polyfill): use `stream` and `events` from deno std/node

---

server/storage/cache.go
server/storage/cache_memory.go
server/storage/cache_memory_lru.go
server/storage/db.go
server/storage/db_postdb.go
server/storage/fs.go
server/storage/fs_local.go
server/storage/fs_local_lru.go
server/storage/storage.go

This doesn't fix the test error that is currently in master yet. Haven't had time to debug.
Just wanted to get this in front of you.
1. Added a cache LRU
2. Added some util functions and make the DB, FS, and Cache interfaces all take the same `options` argument
3. Removed the `err` from the `Has` method
4. Updated the FS LRU implementation to take expiration into account. Didn't think about it, but it would be nice in case TTL is added as an option.

Cache lru and some utils

---

server/storage/cache.go
server/storage/fs_local_lru.go

I introduced a bug in localLRU because `Exists` method logic never set `found`.
Remoing `ToLower` on cache name, because it was breaking my use case, and it is inconsistent.

Fix localLRU and allow for memoryLRU

---

server/storage/fs_local.go

This PR fixes a Windows file path portability error...
```shell
C> go run main.go --port=8080 --dev
...
2021/09/19 12:17:43 [fatal] init storage(fs,local:C:\Users\Roy\go\src\github.com\alephjs\esm.sh\.dev/storage): CreateFile /C:\Users\Roy\go\src\github.com\alephjs\esm.sh\.dev/storage: The filename, directory name, or volume label syntax is incorrect.
```

🛠️ Fix (storage/fs_local) file path portability bug

---

server/query.go

i also removed the part about the types, since it seems to also say that when importing `.js` files

fix grammar for timeout error

---

Dockerfile

hi,
since [esm.sh does not work](https://github.com/alephjs/esm.sh/issues/229), i decided to try to run local instance
found few issues in dockerfile:
* update go - apparently current code doesn't work with go 1.16
* add build cache - to avoid downloading go dependencies each time
* make non-root - ugh... they say it's kinda secure way to do it
* thinner wrapping - this is achieved with `ENTRYPOINT` instruction in dockerfile,
now instead of doing `docker run -e CDN_DOMAIN=localhost -e CACHE=/bla -e DB=/blo ... esm` do `docker run esm --cdn-domain localhost --cache /bla --db /blo ...` (pass through arguments from docker command line)
this also reduces dockerfile maintenance by making container more generic
btw, on windows docker is the only way to run esm.sh
```sh
docker build . -t esm …
```

dockerfile fixes

---

server/dts_transform.go
server/dts_transform_test.go
server/embed/style.css
server/module.go
server/query.go
server/storage/fs.go
server/storage/fs_local.go
server/storage/fs_local_lru.go
server/storage/fs_s3.go

This enforces a more strict contract between fs.Exists and fs.ReadFile, which allows more versatile optimizations within fs.ReadFile for other types of drivers.

return size on fs.Exists and take size on fs.ReadFile

---

server/nodejs.go

Because yarnAdd now runs in an tmp directory, it's hard to ensure it picks up the right registry with just a config file. So just pass it as an arg and be done.

add registry arg to yarn add to fix yarn not using same config

---

server/build.go
server/nodejs.go

For some reason particular packages were permanently in a broken state on certain environments (thee package.json not found error). It took me a while to figure out what persisted data was making the error persist. The hint was that yarn add was still reporting as having succeeded, but it clearly wasn't working. 
Then finally I realized the yarn cache might have something to do with it, so I cleared it, and it fixed the broken state. So that's where these changes are coming from.

For unexpected state after yarn add, run yarn cache clean for that pkg

---

server/build.go
server/dts_transform.go
server/embed/index.html
server/embed/index.js
server/query.go
server/server.go
server/utils.go
test/browser/testing.js

This makes the server much more versatile, and allows for it to exist within strict infrastructure.
- `--basepath` is for everything served that would NOT be from the `cdnDomain`
- `--cdn-basepath` is for everything served from the `cdnDomain` (but does not require `cdnDomain`)
- `--base-redirect` is mostly for debugging or some other unforeseen purpose, it just redirects any request that is not from either of the previously two base paths, to the non-cdn basepath.

support configuring a basepath, cdn-basepath, and base-redirect

---

server/nodejs.go
server/query.go
server/server.go

This PR relates to https://github.com/esm-dev/esm.sh/issues/309
It essentially:
- Makes the Deno check optional (so that esm.sh can still run in a restricted system where the Deno site is unreachable and only an internal NPM registry exists)
- Uses `Http.Get` for it to honour env-defined http proxy URLs

Fix Deno check precluding esm.sh to start

---

server/build.go
server/query.go

Some libs may provide wrong 'side-effect' annotations. As a result, esbuild will remove the side-effect code unexpectedly. 
For this reason esbuild provides [an option named 'IgnoreAnnotations'](https://esbuild.github.io/api/#ignore-annotations):
> It will still do automatic tree shaking of unused imports, however, since that doesn't rely on annotations from developers. Ideally this flag is only a temporary workaround.
---
[ecomfe/zrender](https://github.com/ecomfe/zrender/blob/5.3.2/package.json#L36-L39)(used by [apache/echarts](https://github.com/apache/echarts)) is a realworld example.  [Code below](https://github.com/ecomfe/zrender/blob/559d610bd0a612fa8ed5a7e6a8dd4b23a318e94d/src/all.ts#L7-L8) was removed unexpectedly:
```javascript
registerPainter('canvas', CanvasPainter); …
```

feat(build): add the 'ignore-annotations' option for esbuild

---

.gitignore
server/build.go

When importing a submodule, esm.sh tries to bundle all its local dependencies. If a local module has its 'inner state', it may occur some errors.
---
For example, here's a pkgA
```javascript
pkgA
|-- lib
|    |-- acc.js
|    +-- print.js
+-- index.js
```
The source code in `lib/acc.js` is something like
```javascript
// lib/acc.js
let idx = 0;
export const acc = () => ++idx;
```
The source code in `lib/print.js` is something like
```javascript
// lib/print.js
import { acc } from './acc.js';
export const print = () => console.log(acc())
```
So after building the `lib/print.js` submodule, the `lib/acc.js`'s source code will be included.
When a third party package (pkgB) importing pkgA,
```javascript
// pkgB
import { acc } 'pkgA/lib/acc.js';
import { print } 'pkgA/lib/print.js'
```
It …

feat(build): prevent submodules bundling their local dependencies

---

server/embed/index.html

For self host, no ssl certificates are configured, front-end pages should not automatically jump to http addresses, and I think the jump from http to https should be done by nginx. So here for the non-official website, I removed the automatic jumping logic

Don`t  auto redirect to https for self host

---

server/nodejs.go
server/server.go
server/utils.go

the getOrigin function, always return https scheme address , but for self host , esm.sh is runing on http port.
```
proto := "https"
if host == "localhost" || strings.HasPrefix(host, "localhost:") {
proto = "http"
}
return fmt.Sprintf("%s://%s", proto, host)
```
This allows us to set our server's real address accurately
```
--public-address
```
Instead of a host request header to determine the protocol and address

add --public-address flag

---

README.md

I rewrote part of the readme, so the code-block under "specify external" could use normal JSON and still make sense.
There was a code-block using "jsonc" formatting. Highlight.js doesn't support "jsonc", so the code didn't render on the site. The only reason it used "jsonc" was to add a comment explaining the code. I reworded the accompanying text, in an attempt to explain the code without the comment.

Minor enhancement for website & readme

---

README.md
server/build.go
server/query.go

This pull request adds a `?sourcemap` query, which should make debugging scripts imported from esm.sh easier.
Due to the way esm.sh works, it is made into a boolean and supports `inline` mode only.

Add `?sourcemap` query

---

server/build.go
server/dts_transform.go
server/pkg.go

Currently it uses the 'name' variable as the key of npm dependencies.
https://github.com/ije/esm.sh/blob/4d4294c518d71a66a444ba7932618bd4c0cc3d31/server/build.go#L556-L561
It may miss  when the name contains the submodule path. As an example,
```
import * as p from 'protobufjs/light';
```
the name is 'protobufjs/light' but the package name is 'protobufjs' in the package.json. Stripping submodule path may help.
---
Besides, there are many places doing such things and this pr replaces them with a common method `parsePkgNameInfo`.

fix(build): strip submodule path when using npm dependencies' map

---

HOSTING.md
server/build.go
server/node_services.go
server/nodejs.go
server/server.go

For the business case, I want to self-hosting this server and serve with some private packages hosted on the npm-registry  
- Add the `npm-token` flag to provide NPM private token 
- Add the `.npmrc` file in the temporary yarn installing directory to provide the `_authToken`
- Remove the `--no-default-rc` flag of the `yarn installing` command to support reading `.npmrc`

Add npm private packages support

---

server/nodejs.go
test/baseui/baseui.test.ts

In some cases, package.json (e.g. baseui from https://baseweb.design/) contains the following shims: 
```json
"module": "./dist/index.es.js",
"browser": {
"./dist/index.js": "./dist/browser.es5.js",
"./dist/index.es.js": "./dist/browser.es5.es.js"
},
"es2015": {
"./dist/browser.es5.es.js": "./dist/browser.es2015.es.js"
},
"es2017": {
"./dist/browser.es5.es.js": "./dist/browser.es2017.es.js",
"./dist/browser.es2015.es.js": "./dist/browser.es2017.es.js"
},
```
I believe the behavior is defined in https://github.com/defunctzombie/package-browser-field-spec . 
In such scenarios, esm.sh will fail to un-marshal the package spec.
This attempts to fix it.
The hot fix here is quite naive. It doesn't actually respect the shim. Other approaches are potentially using generics or `json.RawMessage`. …

Fix scenarios where module/es2015 are shims (maps)

---

go.mod

The go version is not correctly set, the 1.16 is too stale to run the server since some dependencies are required at least 1.17.
Upgrade to 1.18 (as same as the Dockerfile)
successfully run the server with the 1.18 at my local

fix: upgrade go version to 1.18

---

server/handler.go

After I set a `basePath` for the server, the redirects also base on the path without the `basePath` which is not the expected behavior.

fix: basePath doesn't take effect on redirects

---

config.example.jsonc
server/config/config.go
server/handler.go
server/nodejs.go

./config.json:
```
"basePath": "/",
"npmRegistry": "https://registry.npmjs.org",
```
Bad Cases:
```
$ curl -D- http://localhost:8080/react
HTTP/1.1 302 Found
...
Location: //react
$ curl -D- http://localhost:8080/react@18.2.0
HTTP/1.1 302 Found
...
Location: http://localhost:8080//react@18.2.0
$ curl -D- http://localhost:8080/react
----server error------------
Get "https://registry.npmjs.orgreact": dial tcp: lookup registry.npmjs.orgreact: no such host
```

fix(conf): some bugs related to package path parsing

---

server/build.go
test/external-bundle/ajv.test.tsx
test/external-bundle/deep-eq.js
test/external-bundle/deno.json
test/external-bundle/import_map.json

fixes #498 
I'm not sure this is correct. I see that default flow is go through 
```go
return api.OnResolveResult{Path: "__ESM_SH_EXTERNAL:" + url, External: true}, nil
```
Then rewrite imports in output files after go compiled it. Don't know why is that.

respect externals arg in bundle mode

---

server/build.go
test/export-all-members/rc-utils.test.tsx

https://unpkg.com/rc-util@5.27.2/es/Dom/dynamicCSS.js 
https://esm.sh/v106/rc-util@5.27.2/es2022/es/Dom/dynamicCSS.js
The module is exported members but will be moved to the default export
Add the reexport members to fix this problem

Default export all members from original module to prevent missing named exports members

---

server/dts_transform.go

This patch is causing issues with recent versions of Preact:
```
error: TS2300 [ERROR]: Duplicate identifier 'PropsWithChildren'.
export type PropsWithChildren<P = unknown> = P & { children?: preact.ComponentChildren };
~~~~~~~~~~~~~~~~~
at https://esm.sh/v106/preact@10.12.1/compat/src/index.d.ts:56:13
TS2300 [ERROR]: Duplicate identifier 'PropsWithChildren'.
export type PropsWithChildren<P = unknown> = P & {
~~~~~~~~~~~~~~~~~
at https://esm.sh/v106/preact@10.12.1/compat/src/index.d.ts:149:14
```

Remove patch for preact/compat types

---

server/handler.go

Update references to `reqOrigin` to use `cdnOrigin`

---

test/bootstrap.ts

Just to count time spent and compare it with the performance improve PR #543

Add test time spent count

---

server/esm.go
test/nested-conditions/nested-conditions.test.ts

This PR is fix resolve the correct `nested conditions export` definition of [package.json](https://unpkg.com/browse/jotai@2.0.3/package.json)
---
Visit https://esm.sh/v111/jotai@2.0.3/es2022/vanilla/utils.js
Resolve to https://unpkg.com/browse/jotai@2.0.3/esm/index.mjs
Resolve to https://unpkg.com/browse/jotai@2.0.3/esm/vanilla/utils.mjs

Fix package nested conditions export

---

CLI.ts

Made the CLI tool work with the specified in deno.json indent size.

CLI: Use user-specified indent size

---

server/build.go
server/config/config.go
server/npm.go
server/utils.go

**Use Case:** Hosting private npm packages in a custom npm registry, [like GitHub's npm registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry), and that npm registry is not a mirror.
**Issue:** When using a custom npm registry you set the `npmRegistry` in the config and it downloads the correct npm package, but if you try and download any other package (such as a dependency) it fails because the custom npm registry does not contain any packages but private ones.
**Solution:** [Use scope in the `.npmrc`](https://docs.npmjs.com/cli/v9/configuring-npm/npmrc?v=true#auth-related-configuration), this seemed the easiest since the `.npmrc` file was being created anyway.
Not sure how to test this, any advice about that would be …

Add scope to config

---

config.example.jsonc

Adds a description and example of scoping the packages fetched from an npm registry.

Add scope to example config

---

config.example.jsonc
server/build.go
server/config/config.go
server/npm.go

Basic auth is necessary in order to support certain registries, this adds support for username and password to the config json file.

Add support for basic auth

---

packages/esm-cjs-lexer/Cargo.lock
packages/esm-cjs-lexer/Cargo.toml
packages/esm-cjs-lexer/src/cjs.rs
packages/esm-cjs-lexer/src/test.rs

Following up on https://twitter.com/lewisl9029/status/1674890868661325829, here's an early version of the PR for detecting minified UMD exports in esm-cjs-lexer. :)
Unfortunately, a lot of the code in here ended up looking rather nasty. I'm still pretty new to Rust, so would love to get some tips from someone more experienced on how the code could be improved! Happy to iterate on the code until you're happy with it.
I've added a number of minimal test cases representing some of the minified UMD patterns I've encountered in the wild (some from webpack, some from rollup). I'm sure there will be more, will tackle them as they come up, feel free to ping me in issues if you see any new cases that needs to be covered going forward!
I've been testing it out in prod by publishing it to this fork: …

Minified UMD detection

---

README.md

The GitHub example isn't working because default exports were added to `tslib` just recently: https://github.com/microsoft/tslib/commit/a0a67d9bf5ac773982e079aec626b9d6ff2060f6 so I upgraded to 2.6.0.
I could also change it to something like:
```typescript
import * as tslib from "https://esm.sh/gh/microsoft/tslib@2.5.0";
```
but I think it's less desirable.
I love esm.sh BTW

Fix import from GitHub example

---

server/embed/polyfills/node_events.js

Hey there, great project, I'm loving using esm.sh :)
I recently ran into a blocker trying to import ipfs/helia via esm.sh: the esm.sh `events` polyfill does not export `setMaxListeners` so the thing broke rather violently. 
this is mostly just copypasta from the core nodejs events src. I see the rest of the polyfill still carries the joyent copyright notice so I assume that's where it came from too. 
I substituted the arg validation from the esm.sh setMaxListener function and removed the node internal eventTarget checking function in favor of simply ducktyping event targets by checking if they have a `setMaxListener` function (this is the second line of defense in the nodejs code). and substituted nodes internal error factory with simply throwing a `TypeError` with a helpful message.
Hope …

add setMaxListeners to events polyfill

---

README.md
packages/esm-worker/src/index.ts
server/server_handler.go
test/esm-worker/esm-worker.test.ts
test/raw/raw.test.ts

As a followup to a Discord discussion, this PR adds an escape hatch via a new `?raw` query (and extra query) to allow requests for raw (untransformed) package source files.
In rare cases, you may want to request JS source files from packages, as-is, without transformation into ES modules. To do so, you would now add a `?raw` query to the request URL.
For example, you might need to register a package's source script as a service worker in a browser that [does not yet support](https://caniuse.com/mdn-api_serviceworker_ecmascript_modules) the `type: "module"` option:
```js
await navigator.serviceWorker.register(
new URL(
"https://esm.sh/playground-elements@0.18.1/playground-service-worker.js?raw", 
import.meta.url.href
), 
{ scope: '/' }
);
```
You could also now alternatively specify an …

Add ?raw to support requests for raw package source files

---

CLI.deno.ts

I wanted to use the esm.sh CLI but noticed it had a few issues, so I decided to try and fix them myself.
- It can now use the `imports` property directly in `deno.json`, which has been the go-to for many since it has been introduced in Deno v1.30 (it should still support external import maps from my testing)
- It now uses `deno fmt` instead of forcing 2 space indent

Improved Deno CLI

---

CLI.deno.ts

- Prevents one-line objects when stringifying JSON
```diff
{
+	"fmt": {
+		"useTabs": true,
+		"semiColons": true,
+		"singleQuote": false
+	}
-	"fmt": { "useTabs": true, "semiColons": true, "singleQuote": false }
}
```
- Adds the `scopes` property if it doesn't exist for whatever reason

Further deno cli improvements

---

config.example.jsonc
server/config/config.go
server/config/config_test.go
server/server_handler.go

This will add support for adding config option for allowed packages and multiple scopes. This is extremely helpful for self-hosted version where you don't want someone looping over every package on npm and ddos your server.
This will:
- add support for multiple scope, not just one
- allow package names
- allow something, ban something
- add tests

Feature Allowlist in config

---

CONTRIBUTING.md

`https://npmjs.org/registry` -> `https://registry.npmjs.org`

Fix example registry URL in CONTRIBUTING.md

---

packages/esm-cjs-lexer/src/cjs.rs
packages/esm-cjs-lexer/src/test.rs

Hi there! This PR adds a fix for a minified UMD package ([ttag](https://www.npmjs.com/package/ttag)) that we didn't handle properly due to the hard-coded indices on statements inside the UMD fn body for detecting webpack's `.d` and `.r` calls.
You can repo by pasting this into the esm.sh playground:
```js
import * as ttag from "https://esm.sh/ttag";
console.log('ttag', ttag)
```
Note that we only see a default export even though the package has a whole bunch of named exports that we should be detecting.
This new implementation now uses some slightly smarter heuristics to determine indices in some places (skipping 1 index only if we detect "use strict"), and searches the entire list of statements until we find one that matches the expected shape in others. I added a few new test cases that …

Detect minified umd with leading fn declarations

---

packages/esm-cjslexer/src/cjs.rs
packages/esm-cjslexer/src/test.rs

Hi there! Back again with another minified umd detection PR, this time handling webpack 3's output for the [highcharts-react-official](https://www.npmjs.com/package/highcharts-react-official) library.
Luckily, it looks like the only material difference in output between 3 and 4 is the statement order, so all that was needed to fix the test was to handle both positions.
Btw, when did the playground start adding ?dev to all imports? Is there a way to override this for repro'ing prod issues? When I first tried to repro this I was surprised to see it working in the playground. Turns out it only works because of the dev flag (presumably because the dev version uses one of the non-minified builds?).

Handle webpack 3 minified umd

---

.github/workflows/test.yml
server/build.go
server/build_resolver.go
server/build_rewriter.go
server/dts_transform.go
server/esm_path.go
server/esm_routes.go
server/utils.go
test/pkg.pr.new/test.ts

Support `https://pkg.pr.new/...` dependency

---

go.mod
go.sum
server/esm_router.go
server/server.go
test/cors/cors.test.ts

the default "Access-Control-Allow-Methods" header is "GET, HEAD, POST", no need to set.
see https://www.w3.org/TR/2020/SPSD-cors-20200602/#simple-cross-origin-request-0

Remove 'Access-Control-Allow-Methods' header

---

server/build_resolver.go
server/npm.go
server/path.go
server/router.go
server/utils.go
test/jsr/other.ts

Support 'major.minor.patch+build' versioning

---

server/build_resolver.go
server/dts_transform.go
server/router.go
test/issue-791/test.ts

Support `.d.cts` types

---

server/router.go
test/fix-url/test.ts

Fix build save path with '?external=*'

---

server/fetch.go
server/git.go
server/legacy_router.go
server/npm.go
server/router.go
server/server.go
test/legacy-routes/test.ts

```
https://esm.sh/v135/@jitl/quickjs-ng-wasmfile-release-sync@0.31.0/es2022/emscripten-module.wasm -> https://esm.sh/@jitl/quickjs-ng-wasmfile-release-sync@0.31.0/dist/emscripten-module.wasm
```
close #1072

Fix legacy redirects

---

server/build.go
test/node-polyfill/browser-excluded.test.ts
test/node-polyfill/polyfill.test.ts

only when `browser` excluded:
```json
{
"browser": {
"node:buffer": false
}
}
```

Use global `Buffer` and `process`

---

server/build_resolver.go
test/issue-1161/test.ts

Fixes #1161  and https://github.com/modelcontextprotocol/typescript-sdk/issues/293
Why?
MCP's package.json doesn't follow the expected values. It looks like:
```json
"exports": {
"./*": {
"import": "./dist/esm/*",
"require": "./dist/cjs/*"
}
},
```
But the code expects the values to include the extension.
This handles that by searching for the extension that is actually present (as happens in other cases)

Call finalizeBuildEntry for exportEntries generated from asteriskPath objects

---

internal/npm/npm.go
internal/npm/npm_test.go

This is a follow up fix to #1152
I noticed that when choosing a version of a package by a date, the service was sometimes choosing "experimental" or "alpha" versions which I don't think it should do. This filters those out so that it chooses the latest "stable" version as of that date.

only use stable versions when resolving by date

---

server/router.go

Fix `cache-control` header for 404 requests

---

config.example.jsonc
internal/storage/migration.go
internal/storage/migration_test.go
internal/storage/storage.go
internal/storage/storage_fs.go
internal/storage/storage_fs_test.go
internal/storage/storage_s3.go
server/config.go
server/router.go
server/server.go

when switching the current storage to a new storage, the migration storage will copy the files from the old storage to the new storage lazily, to avoid breaking deno.lock

Migration storage
